### PR TITLE
Update localities and neighbourhoods in Nigeria

### PR DESCRIPTION
**Pull request by stepps00**
Fixes https://github.com/whosonfirst-data/whosonfirst-data/issues/2015

This PR updates neighbourhoods in Lagos, Nigeria and localities around the country.

To do:
- [x] Update existing neighbourhoods
- [x] Update existing localities
- [x] Add missing neighbourhoods
- [x] Add missing localities
- [x] Supersede duplicate records, as needed
- [x] Demote overlapping locality points to neighbourhood placetype
- [x] PIP
- [x] Validate geometries and properties

### CODE REVIEW

**Comment by stepps00** [comment]
_New coverage of locality polygons in Nigeria_
Screen Shot 2022-11-16 at 12 04 44 PM

_New coverage of neighbourhood polygons in Lagos_
Screen Shot 2022-11-16 at 12 06 10 PM

_New coverage of locality + neighbourhood polygons in the greater Lagos area_
Screen Shot 2022-11-16 at 12 06 24 PM

**Comment by stepps00** [comment]
Over to @nvkelso to review.

**Review by nvkelso — APPROVED** [review]
We reviewed this heads up in QGIS, and spot checked in this PR.

**Comment by stepps00** [comment]
The most recent commit includes PIP work for all records / descendants in this branch. All properties and geometries have been verified, too.

**Pull request merged**
